# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- task: Npm@1
displayName: 'Installing Modules in Server'
  inputs:
    command: 'install'
    workingDir: 'server'

- task: Npm@1
displayName: 'Installing Modules in Client'
  inputs:
    command: 'install'
    workingDir: 'client'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'server'
    customCommand: 'npm run start'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'client'
    customCommand: 'npm start'

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'
